//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Info_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student_Details
    {
        public int Id { get; set; }

        [Display(Name = "Student Name")]
        [Required(ErrorMessage ="*")]
        public string name { get; set; }

        [Display(Name = "Student Gender")]
        [Required(ErrorMessage = "*")]
        public string gender { get; set; }

        [Display(Name = "Student Age")]
        [Required(ErrorMessage = "*")]
        public int age { get; set; }

        [Display(Name = "Student Standard")]
        [Required(ErrorMessage = "*")]
        public int standard { get; set; }
    }
}
